services:
  - type: web
    name: tds-virtual-ta
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_gemini:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false 